---
version: "2.0"

services:
  web:
    image: baktun/akashlytics:0.10.3
    expose:
      - port: 3080
        as: 80
        accept:
          - beta.akashlytics.com
          - www.akashlytics.com
          - akashlytics.com
        to:
          - global: true
      - port: 3081
        as: 3081
        to:
          - global: false

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 1
        memory:
          size: 2Gi
        storage:
          size: 20Gi
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        web:
          denom: uakt
          amount: 1000

deployment:
  web:
    dcloud:
      profile: web
      count: 1
