services:
  web:
    image: baktun/akashlytics-web
    container_name: akashlytics-web
    build:
      context: app/
      dockerfile: Dockerfile
    ports:
      - "3000:80"
  api:
    image: baktun/akashlytics-api
    container_name: akashlytics-api
    environment:
      - AKASHLYTICS_CORS_WEBSITE_URLS=http://localhost:3080
    build:
      context: api/
      dockerfile: Dockerfile
    ports:
      - "3080:3080"
