import { GeneratedType } from "@cosmjs/proto-signing";
import * as akash_audit_v1beta1_audit_types from "./akash/audit/v1beta1/audit";
import * as akash_audit_v1beta2_audit_types from "./akash/audit/v1beta2/audit";
import * as akash_cert_v1beta2_cert_types from "./akash/cert/v1beta2/cert";
import * as akash_deployment_v1beta1_deployment_types from "./akash/deployment/v1beta1/deployment";
import * as akash_deployment_v1beta1_group_types from "./akash/deployment/v1beta1/group";
import * as akash_deployment_v1beta2_deploymentmsg_types from "./akash/deployment/v1beta2/deploymentmsg";
import * as akash_deployment_v1beta2_groupmsg_types from "./akash/deployment/v1beta2/groupmsg";
import * as akash_market_v1beta2_bid_types from "./akash/market/v1beta2/bid";
import * as akash_market_v1beta2_lease_types from "./akash/market/v1beta2/lease";
import * as akash_provider_v1beta1_provider_types from "./akash/provider/v1beta1/provider";
import * as akash_provider_v1beta2_provider_types from "./akash/provider/v1beta2/provider";
export const akashTypes: ReadonlyArray<[string, GeneratedType]> = [["/akash.audit.v1beta1.audit.MsgSignProviderAttributes",akash_audit_v1beta1_audit_types.MsgSignProviderAttributes],
["/akash.audit.v1beta1.audit.MsgSignProviderAttributesResponse",akash_audit_v1beta1_audit_types.MsgSignProviderAttributesResponse],
["/akash.audit.v1beta1.audit.MsgDeleteProviderAttributes",akash_audit_v1beta1_audit_types.MsgDeleteProviderAttributes],
["/akash.audit.v1beta1.audit.MsgDeleteProviderAttributesResponse",akash_audit_v1beta1_audit_types.MsgDeleteProviderAttributesResponse],
["/akash.audit.v1beta2.audit.MsgSignProviderAttributes",akash_audit_v1beta2_audit_types.MsgSignProviderAttributes],
["/akash.audit.v1beta2.audit.MsgSignProviderAttributesResponse",akash_audit_v1beta2_audit_types.MsgSignProviderAttributesResponse],
["/akash.audit.v1beta2.audit.MsgDeleteProviderAttributes",akash_audit_v1beta2_audit_types.MsgDeleteProviderAttributes],
["/akash.audit.v1beta2.audit.MsgDeleteProviderAttributesResponse",akash_audit_v1beta2_audit_types.MsgDeleteProviderAttributesResponse],
["/akash.cert.v1beta2.cert.MsgCreateCertificate",akash_cert_v1beta2_cert_types.MsgCreateCertificate],
["/akash.cert.v1beta2.cert.MsgCreateCertificateResponse",akash_cert_v1beta2_cert_types.MsgCreateCertificateResponse],
["/akash.cert.v1beta2.cert.MsgRevokeCertificate",akash_cert_v1beta2_cert_types.MsgRevokeCertificate],
["/akash.cert.v1beta2.cert.MsgRevokeCertificateResponse",akash_cert_v1beta2_cert_types.MsgRevokeCertificateResponse],
["/akash.deployment.v1beta1.deployment.MsgCreateDeployment",akash_deployment_v1beta1_deployment_types.MsgCreateDeployment],
["/akash.deployment.v1beta1.deployment.MsgCreateDeploymentResponse",akash_deployment_v1beta1_deployment_types.MsgCreateDeploymentResponse],
["/akash.deployment.v1beta1.deployment.MsgDepositDeployment",akash_deployment_v1beta1_deployment_types.MsgDepositDeployment],
["/akash.deployment.v1beta1.deployment.MsgDepositDeploymentResponse",akash_deployment_v1beta1_deployment_types.MsgDepositDeploymentResponse],
["/akash.deployment.v1beta1.deployment.MsgUpdateDeployment",akash_deployment_v1beta1_deployment_types.MsgUpdateDeployment],
["/akash.deployment.v1beta1.deployment.MsgUpdateDeploymentResponse",akash_deployment_v1beta1_deployment_types.MsgUpdateDeploymentResponse],
["/akash.deployment.v1beta1.deployment.MsgCloseDeployment",akash_deployment_v1beta1_deployment_types.MsgCloseDeployment],
["/akash.deployment.v1beta1.deployment.MsgCloseDeploymentResponse",akash_deployment_v1beta1_deployment_types.MsgCloseDeploymentResponse],
["/akash.deployment.v1beta1.group.MsgCloseGroup",akash_deployment_v1beta1_group_types.MsgCloseGroup],
["/akash.deployment.v1beta1.group.MsgCloseGroupResponse",akash_deployment_v1beta1_group_types.MsgCloseGroupResponse],
["/akash.deployment.v1beta1.group.MsgPauseGroup",akash_deployment_v1beta1_group_types.MsgPauseGroup],
["/akash.deployment.v1beta1.group.MsgPauseGroupResponse",akash_deployment_v1beta1_group_types.MsgPauseGroupResponse],
["/akash.deployment.v1beta1.group.MsgStartGroup",akash_deployment_v1beta1_group_types.MsgStartGroup],
["/akash.deployment.v1beta1.group.MsgStartGroupResponse",akash_deployment_v1beta1_group_types.MsgStartGroupResponse],
["/akash.deployment.v1beta2.deploymentmsg.MsgCreateDeployment",akash_deployment_v1beta2_deploymentmsg_types.MsgCreateDeployment],
["/akash.deployment.v1beta2.deploymentmsg.MsgCreateDeploymentResponse",akash_deployment_v1beta2_deploymentmsg_types.MsgCreateDeploymentResponse],
["/akash.deployment.v1beta2.deploymentmsg.MsgDepositDeployment",akash_deployment_v1beta2_deploymentmsg_types.MsgDepositDeployment],
["/akash.deployment.v1beta2.deploymentmsg.MsgDepositDeploymentResponse",akash_deployment_v1beta2_deploymentmsg_types.MsgDepositDeploymentResponse],
["/akash.deployment.v1beta2.deploymentmsg.MsgUpdateDeployment",akash_deployment_v1beta2_deploymentmsg_types.MsgUpdateDeployment],
["/akash.deployment.v1beta2.deploymentmsg.MsgUpdateDeploymentResponse",akash_deployment_v1beta2_deploymentmsg_types.MsgUpdateDeploymentResponse],
["/akash.deployment.v1beta2.deploymentmsg.MsgCloseDeployment",akash_deployment_v1beta2_deploymentmsg_types.MsgCloseDeployment],
["/akash.deployment.v1beta2.deploymentmsg.MsgCloseDeploymentResponse",akash_deployment_v1beta2_deploymentmsg_types.MsgCloseDeploymentResponse],
["/akash.deployment.v1beta2.groupmsg.MsgCloseGroup",akash_deployment_v1beta2_groupmsg_types.MsgCloseGroup],
["/akash.deployment.v1beta2.groupmsg.MsgCloseGroupResponse",akash_deployment_v1beta2_groupmsg_types.MsgCloseGroupResponse],
["/akash.deployment.v1beta2.groupmsg.MsgPauseGroup",akash_deployment_v1beta2_groupmsg_types.MsgPauseGroup],
["/akash.deployment.v1beta2.groupmsg.MsgPauseGroupResponse",akash_deployment_v1beta2_groupmsg_types.MsgPauseGroupResponse],
["/akash.deployment.v1beta2.groupmsg.MsgStartGroup",akash_deployment_v1beta2_groupmsg_types.MsgStartGroup],
["/akash.deployment.v1beta2.groupmsg.MsgStartGroupResponse",akash_deployment_v1beta2_groupmsg_types.MsgStartGroupResponse],
["/akash.market.v1beta2.bid.MsgCreateBid",akash_market_v1beta2_bid_types.MsgCreateBid],
["/akash.market.v1beta2.bid.MsgCreateBidResponse",akash_market_v1beta2_bid_types.MsgCreateBidResponse],
["/akash.market.v1beta2.bid.MsgCloseBid",akash_market_v1beta2_bid_types.MsgCloseBid],
["/akash.market.v1beta2.bid.MsgCloseBidResponse",akash_market_v1beta2_bid_types.MsgCloseBidResponse],
["/akash.market.v1beta2.lease.MsgCreateLease",akash_market_v1beta2_lease_types.MsgCreateLease],
["/akash.market.v1beta2.lease.MsgCreateLeaseResponse",akash_market_v1beta2_lease_types.MsgCreateLeaseResponse],
["/akash.market.v1beta2.lease.MsgWithdrawLease",akash_market_v1beta2_lease_types.MsgWithdrawLease],
["/akash.market.v1beta2.lease.MsgWithdrawLeaseResponse",akash_market_v1beta2_lease_types.MsgWithdrawLeaseResponse],
["/akash.market.v1beta2.lease.MsgCloseLease",akash_market_v1beta2_lease_types.MsgCloseLease],
["/akash.market.v1beta2.lease.MsgCloseLeaseResponse",akash_market_v1beta2_lease_types.MsgCloseLeaseResponse],
["/akash.provider.v1beta1.provider.MsgCreateProvider",akash_provider_v1beta1_provider_types.MsgCreateProvider],
["/akash.provider.v1beta1.provider.MsgCreateProviderResponse",akash_provider_v1beta1_provider_types.MsgCreateProviderResponse],
["/akash.provider.v1beta1.provider.MsgUpdateProvider",akash_provider_v1beta1_provider_types.MsgUpdateProvider],
["/akash.provider.v1beta1.provider.MsgUpdateProviderResponse",akash_provider_v1beta1_provider_types.MsgUpdateProviderResponse],
["/akash.provider.v1beta1.provider.MsgDeleteProvider",akash_provider_v1beta1_provider_types.MsgDeleteProvider],
["/akash.provider.v1beta1.provider.MsgDeleteProviderResponse",akash_provider_v1beta1_provider_types.MsgDeleteProviderResponse],
["/akash.provider.v1beta2.provider.MsgCreateProvider",akash_provider_v1beta2_provider_types.MsgCreateProvider],
["/akash.provider.v1beta2.provider.MsgCreateProviderResponse",akash_provider_v1beta2_provider_types.MsgCreateProviderResponse],
["/akash.provider.v1beta2.provider.MsgUpdateProvider",akash_provider_v1beta2_provider_types.MsgUpdateProvider],
["/akash.provider.v1beta2.provider.MsgUpdateProviderResponse",akash_provider_v1beta2_provider_types.MsgUpdateProviderResponse],
["/akash.provider.v1beta2.provider.MsgDeleteProvider",akash_provider_v1beta2_provider_types.MsgDeleteProvider],
["/akash.provider.v1beta2.provider.MsgDeleteProviderResponse",akash_provider_v1beta2_provider_types.MsgDeleteProviderResponse]];
